##
##  Agentic Software Engineering (ASE)
##  Copyright (c) 2025-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under Apache 2.0 <https://spdx.org/licenses/Apache-2.0>
##

#   [top-level] (internal): just pass-through "npm install" operation
post-install
    execa -c plugin npm install && \
    execa -c tool   npm install && \
    execa -c pages  npm install

#   [top-level] update package.json files
upd
    npx -y upd && \
    execa -c plugin npx -y upd && \
    execa -c tool   npx -y upd && \
    execa -c pages  npx -y upd

#   [top-level] show project statistics
tokei
    tokei \
        etc docs bin \
        plugin/etc plugin/agents plugin/hooks plugin/meta plugin/skills \
        tool/etc tool/src/ \
        pages/etc pages/src

#   [top-level] lint project
lint
    execa -c plugin npm start lint && \
    execa -c tool   npm start lint && \
    execa -c pages  npm start lint

#   [top-level] build project
build
    execa -c plugin npm start build && \
    execa -c tool   npm start build && \
    execa -c pages  npm start build

#   [top-level] publish new release of project
publish [hostname=en4.*]
    execa -c plugin npm start lint && \
    execa -c tool   npm start lint && \
    execa -c pages  npm start lint && \
    bump="R"; \
    case "$*" in -b* ) bump=`echo "$*" | sed -e 's;^-i;;'` ;; esac; \
    node etc/version.mts "$bump" && \
    execa -c plugin npm start build && \
    execa -c tool   npm start build && \
    version="$(qq -r .version package.json)"
    git commit \
        -m "update version to $version" \
        package.json \
        tool/package.json \
        plugin/package.json \
        plugin/.claude-plugin/plugin.json \
        plugin/.github/plugin/plugin.json \
        plugin/.codex-plugin/plugin.json \
        pages/package.json && \
    git tag "$version" && \
    git push && \
    git push --tags && \
    (cd tool && npm publish) && \
    V=`echo "$version" | sed -e 's;\.;\\.;g'` && \
    sed -n -e "/^${V} /, /^[0-9]\\./ { /^${V} /p; /^[0-9]\\./!p; }" <CHANGELOG.md >.notes.md && \
    gh release create --title "ASE $version" --notes-file .notes.md --verify-tag $version && \
    rm -f .notes.md

#   [top-level] remove regularly built files
clean
    execa -c plugin npm start clean && \
    execa -c tool   npm start clean && \
    execa -c pages  npm start clean && \
    shx rm -rf dst

#   [top-level] remove all built files
distclean: clean
    execa -c plugin npm start distclean && \
    execa -c tool   npm start distclean && \
    execa -c pages  npm start distclean && \
    shx rm -f package-lock.json && \
    shx rm -rf node_modules

