##
##  Agentic Software Engineering (ASE)
##  Copyright (c) 2025-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under Apache 2.0 <https://spdx.org/licenses/Apache-2.0>
##

#   [pages] lint project (type-check and static code analysis)
lint
    astro check --config etc/astro.config.mjs && \
    eslint --config etc/eslint.mjs "src/**/*.{ts,astro}"

#   [pages] build project
build : lint
    astro build --config etc/astro.config.mjs

#   [pages] development target
dev
    astro dev --config etc/astro.config.mjs

#   [pages] preview website
preview
    astro preview --config etc/astro.config.mjs

#   [pages] record the Typing-Demo component as an animated GIF
typing-demo: build
    node etc/typing-demo.mjs

#   [pages] remove website
clean
    shx rm -rf dst

#   [pages] remove all built files
distclean: clean
    shx rm -f package-lock.json
    shx rm -rf node_modules

