##
##  Agentic Software Engineering (ASE)
##  Copyright (c) 2025-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

name: Deploy static content to Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Install dependencies
        working-directory: pages
        run: npm install
      - name: Build website
        working-directory: pages
        env:
          SITE_URL: https://ase.tools
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "pages/dst"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

